113 postgres initial load
openkfw/Oscar pull request #131
Opened 2022-06-06 08:12 UTC by bariela

closes #113 

## Description

implemented postgres database option in initial-data-load

## Motivation and Context

## How has this been tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have checked to ensure that there aren't other open [Pull Requests](../../../pulls) for the same update/change.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-20 16:25 UTC, MartinJurcoGlina requested changes

2022-06-20 16:25 UTC, MartinJurcoGlina commented on minikube/docker-compose.manual-services.yml
>      volumes:
we won't need volumes at all as we're using typescript that is being built in Dockerfile and for copying data config there is script

2022-06-21 08:31 UTC, bariela commented on initial-data-load/src/mapLayers/layersGeoDataUpload.ts
> +const bbox: any = require('@turf/bbox');
bbox was causing type issue, when imported, this was quick fix. Can we keep it this way?

2022-06-21 08:32 UTC, MartinJurcoGlina commented on initial-data-load/src/mapLayers/layersGeoDataUpload.ts
> +const bbox: any = require('@turf/bbox');
alright

2022-06-21 09:01 UTC, MartinJurcoGlina approved these changes

2022-06-21 09:01 UTC, merged