Get map layers with or without geodata
openkfw/Oscar pull request #77
Opened 2021-10-10 20:52 UTC by srezacova

## Description

Refactor getMapLayers function to return map layers with or without geoData. 

## How has this been tested?

1. Create initial-data-load/data/testCountry4 folder
2. Copy  initial-data-load/data/MapLayers.yml to testCountry4 folder
3. Add COUNTRY=testCountry4 to .env file
4. run ./start.sh
5. run ./runinitialload.sh
6. In UI map layers click on Select layers
7. You can see all these layers there even if they do not have geoData in database
8. Check the same for testCountry, to see if layers with geoData are uploaded properly

## Screenshots (if appropriate):

## Types of changes

- [ X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X ] I have read the **CONTRIBUTING** document.
- [X ] I have checked to ensure that there aren't other open [Pull Requests](../../../pulls) for the same update/change.
- [X ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ X] All new and existing tests passed.

2021-10-11 07:26 UTC, bariela requested changes
scenarios need to be tested in automated way to avoid future issues :)

2021-10-11 07:26 UTC, bariela commented on api/src/actions/mapLayersActions.js
> +const getMapLayers = async () => {
can you add doc comment to the function when you are modifying it?

2021-10-11 07:26 UTC, bariela commented on api/src/actions/mapLayersActions.js
> +const getMapLayers = async () => {
this one function actually still fulfils the previous name, it is returning the mapLayers with link to geojson file from different collection. We should keep the name after all.

2021-10-11 07:26 UTC, bariela commented on api/src/tests/staticLayers.js
> -  it('should return empty array, if no geojson data in db', async () => {
please don't remove test, but modify it. In the PR you wrote quite nice scenario and this one test needs only change in description and on L21 to expect the one layer

2021-11-04 17:59 UTC, srezacova commented
Hi, I have just few questions. 
1) getGeojsonData function in vectorSourceLoader and boxVectorSourceLoader return exactly the same structure? I just have some problem with debugging on frontend so I cannot show it in console. In case of boxVectorSourceLoader it is still geojsonData?
2)Error I mentioned in point 9 is:
```
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'protocol')

  92 | export const getGeojsonData = async (url) => {
> 93 |   const response = await axios.get(url);
  94 |   return response.data;
  95 | };
```
I can get rid of it by adding something like this:
```
      if (url) {
        response = await getGeojsonData(url);
      }
```
but I am not sure if it is necessary. Then I need to also put
`        handleIsLoading(title, 'remove');`
to  LN76. And in points.js on LN11 there is also condition that depends on geoReferenceId, that I must change if I do these changes.
3)In the first test when I will try to expect something like this:
`    expect(res.body[0].layerType).toEqual(mapLayerWithoutGeodata.layerType);`
It will not work, it uses MapLayer model which uses MapLayerSchema which do not include layerType. But when we are getting data with getMapLayers function, we use exactly the same MapLayer model and it return all properties we have in database layerType included. Whats the reason? Should I use SingleMapLayer discriminator instead?

2021-11-04 19:01 UTC, srezacova commented on api/src/tests/staticLayers.js
> +});
Removed, thanks for noting.

2021-11-04 19:02 UTC, srezacova commented on api/src/tests/staticLayers.js
> +    expect(res.body).toHaveLength(1);
I added some. Please check again.

2021-11-05 10:28 UTC, bariela commented
@srezacova hi,
1. it is literally the same function, so definitely yes. Difference might be only in code of the respective loaders
2. sounds reasonable, but also with else (returning probably just [] ?)
3. definitely the discriminator, the model itself is just some common parts for both of them

2021-11-05 10:29 UTC, bariela requested changes
the discriminator should resolve problem in test

2021-11-05 10:29 UTC, bariela commented on api/src/tests/staticLayers.js
> +    expect(res.body).toHaveLength(1);
also that there is really no geoReferenceId or geoDataUrl

2021-11-07 21:04 UTC, srezacova commented
> @srezacova hi,
> 
> 1. it is literally the same function, so definitely yes. Difference might be only in code of the respective loaders
> 2. sounds reasonable, but also with else (returning probably just [] ?)
> 3. definitely the discriminator, the model itself is just some common parts for both of them

2. I fixed this in VectorSourceLoader. You can test it with layer with no geoReferenceId.In case that normal mapLayers wouldn't have in some case geoReferenceId, what to do with condition on LN10 in points.js? Now it uses Kobo loader for these layers. Will this case ever happen for normal mapLayers? If not I will leave it like this.
3. I put discriminator in first test, but it will not work for second test with:
```
        color: {
          type: 'colormap',
          value: 'green',
        },
```
in legend, because SingleMapLayer is expecting color as string. Thats probably the reason why we used MapLayer model there? 
getMapLayers function in mapLayersModel.js return are all map layers properties even those that are not in MapLayer model. (for example layerType) Why? It should only return those properties that are in MapLayerSchema or not?
Thanks for answer

2021-11-07 21:04 UTC, srezacova commented on api/src/tests/staticLayers.js
> +    expect(res.body).toHaveLength(1);
I fixed that. Please check again.

2021-11-10 10:02 UTC, bariela commented
> > @srezacova hi,
> > 
> > 1. it is literally the same function, so definitely yes. Difference might be only in code of the respective loaders
> > 2. sounds reasonable, but also with else (returning probably just [] ?)
> > 3. definitely the discriminator, the model itself is just some common parts for both of them
> 
> 1. I fixed this in VectorSourceLoader. You can test it with layer with no geoReferenceId.In case that normal mapLayers wouldn't have in some case geoReferenceId, what to do with condition on LN10 in points.js? Now it uses Kobo loader for these layers. Will this case ever happen for normal mapLayers? If not I will leave it like this.
> 2. I put discriminator in first test, but it will not work for second test with:
> 
> ```
>         color: {
>           type: 'colormap',
>           value: 'green',
>         },
> ```
> 
> in legend, because SingleMapLayer is expecting color as string. Thats probably the reason why we used MapLayer model there? getMapLayers function in mapLayersModel.js return are all map layers properties even those that are not in MapLayer model. (for example layerType) Why? It should only return those properties that are in MapLayerSchema or not? Thanks for answer

Hi,
2. I would resolve already in axiosRequests.js, so the loader gets just correct data format. Maybe even try catch and finally? So error in one data won't break the map
3. color as string is correct for all models, type is on the same level, it is slightly different format from style. It is filtered at creating/saving to db. That is the point of having models.
For getMapLayers we use MapLayer model to get both single and group map layers = layers from all discriminators

I realised just now one new issue - we should not return mapLayers of layerType='regions' with no geoData. Using the old filter & adding condition for layerType 'points' here https://github.com/openkfw/Oscar/pull/77/files#diff-4401c75e5a0122ab94518d56931c9b5eb06c7a1af2764942c5c4b7d050dd9750L18 could work with this requirement.

2021-11-24 16:02 UTC, merged